host ipmi_B12_ru06-07_node1 {
  hardware ethernet 90:5A:08:18:3E:14;
  fixed-address 10.213.118.84;
}

host ipmi_B12_ru06-07_node2 {
  hardware ethernet 90:5A:08:18:3E:16;
  fixed-address 10.213.118.85;
}

host ipmi_B12_ru06-07_node3 {
  hardware ethernet 90:5A:08:18:3E:0F;
  fixed-address 10.213.118.86;
}

host ipmi_B12_ru06-07_node4 {
  hardware ethernet 90:5A:08:18:3D:DE;
  fixed-address 10.213.118.87;
}
