from datetime import datetime, timezone

import paramiko

from .exceptions import DhcpApplyError


_DHCP_CONF = "/etc/dhcp/dhcpd.conf"
_DHCP_TEMPLATE = "/etc/dhcp/dhcpd.conf.template"
_DHCP_TMP = "/etc/dhcp/dhcpd.conf.new"

_BASE_TEMPLATE = """\
# DHCP Server Configuration
# Auto-generated by DHCP provisioning automation

option domain-name "latitude.co";
option domain-name-servers 8.8.8.8, 8.8.4.4;

default-lease-time 600;
max-lease-time 7200;

ddns-update-style none;

authoritative;

# ============================================================================
# IPMI HOST ENTRIES - Managed by automation
# ============================================================================
"""


def _exec_sudo(ssh: paramiko.SSHClient, password: str, command: str) -> tuple[int, str]:
    """Run a sudo -S command, feeding the password via stdin.

    Returns (exit_code, combined_output). stderr is included in the output
    string since that is where dhcpd -t writes its diagnostics.
    """
    stdin, stdout, stderr = ssh.exec_command(f"sudo -S {command}")
    stdin.write(password + "\n")
    stdin.flush()
    exit_code = stdout.channel.recv_exit_status()
    out = stdout.read().decode()
    err = stderr.read().decode()
    return exit_code, (out + err).strip()


def _write_file_sudo(
    ssh: paramiko.SSHClient, password: str, remote_path: str, content: str
) -> tuple[int, str]:
    """Write content to a remote path via "sudo -S tee <path> > /dev/null".

    Sends password on the first line of stdin, then the file content, then
    closes the write channel so tee reaches EOF.
    """
    stdin, stdout, stderr = ssh.exec_command(f"sudo -S tee {remote_path} > /dev/null")
    stdin.write(password + "\n")
    stdin.write(content)
    stdin.channel.shutdown_write()
    exit_code = stdout.channel.recv_exit_status()
    err = stderr.read().decode().strip()
    return exit_code, err


def apply_to_server(
    content: str,
    host: str,
    user: str,
    password: str,
) -> tuple[bool, str]:
    """Apply a DHCP host block to the remote DHCP server.

    Steps (all-or-nothing — if any step fails, dhcpd.conf is NOT changed):
      1. Connect via SSH.
      2. Backup existing dhcpd.conf → dhcpd.conf.bak.<utc-timestamp>.
      3. Read /etc/dhcp/dhcpd.conf.template (fall back to embedded base config).
      4. Assemble full config: template + content.
      5. Write to /etc/dhcp/dhcpd.conf.new via sudo tee.
      6. Validate with "sudo dhcpd -t -cf dhcpd.conf.new".
      7. Move dhcpd.conf.new → dhcpd.conf.
      8. Restart isc-dhcp-server; verify "active".

    Raises DhcpApplyError on any unrecoverable failure so the orchestrator
    can propagate a structured error rather than a bare (False, msg) return.
    Returns (True, message) on success.
    """
    ssh = paramiko.SSHClient()
    ssh.set_missing_host_key_policy(paramiko.AutoAddPolicy())

    try:
        ssh.connect(host, username=user, password=password, timeout=30)
    except Exception as exc:
        raise DhcpApplyError(f"SSH connection to DHCP server {host} failed: {exc}") from exc

    try:
        # 1. Backup
        ts = datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ")
        bak_path = f"{_DHCP_CONF}.bak.{ts}"
        code, out = _exec_sudo(ssh, password, f"cp {_DHCP_CONF} {bak_path}")
        if code != 0:
            raise DhcpApplyError(f"Backup failed ({bak_path}): {out}")

        # 2. Read template
        _, stdout_t, _ = ssh.exec_command(f"cat {_DHCP_TEMPLATE} 2>/dev/null || echo ''")
        template = stdout_t.read().decode()
        if not template.strip():
            template = _BASE_TEMPLATE

        # 3. Assemble full config
        updated_at = datetime.now(timezone.utc).isoformat()
        full_config = template.rstrip("\n") + f"\n\n# Last updated: {updated_at}\n\n" + content + "\n"

        # 4. Write to temp
        code, err = _write_file_sudo(ssh, password, _DHCP_TMP, full_config)
        if code != 0:
            raise DhcpApplyError(f"Failed to write temp config {_DHCP_TMP}: {err}")

        # 5. Validate
        code, out = _exec_sudo(ssh, password, f"dhcpd -t -cf {_DHCP_TMP}")
        if code != 0:
            _exec_sudo(ssh, password, f"rm -f {_DHCP_TMP}")
            raise DhcpApplyError(
                f"dhcpd -t validation failed — original dhcpd.conf is intact:\n{out}"
            )

        # 6. Move into place
        code, out = _exec_sudo(ssh, password, f"mv {_DHCP_TMP} {_DHCP_CONF}")
        if code != 0:
            raise DhcpApplyError(f"mv to {_DHCP_CONF} failed: {out}")

        # 7. Restart
        code, out = _exec_sudo(ssh, password, "systemctl restart isc-dhcp-server")
        if code != 0:
            raise DhcpApplyError(f"systemctl restart isc-dhcp-server failed: {out}")

        # 8. Verify active
        code, status = _exec_sudo(ssh, password, "systemctl is-active isc-dhcp-server")
        status = status.strip()
        if status != "active":
            raise DhcpApplyError(
                f"dhcpd.conf applied and service restarted, but service status is '{status}'"
            )

        return True, f"dhcpd.conf applied and service is active. Backup at {bak_path}."

    finally:
        ssh.close()
